{
 "title": "Automated Sensor Dashboard - DSI",
 "refresh": "5s",
 "panels": [
  {
   "title": "Device 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_1\") AS \"IR Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_1\") AS \"K Type Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_1\") AS \"Current Miller Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_1\") AS \"Current Mixer Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    }
   ]
  },
  {
   "title": "Device 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_2\") AS \"IR Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_2\") AS \"K Type Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_2\") AS \"Current Miller Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_2\") AS \"Current Mixer Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    }
   ]
  },
  {
   "title": "Device 3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_3\") AS \"IR Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_3\") AS \"K Type Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_3\") AS \"Current Miller Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_3\") AS \"Current Mixer Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    }
   ]
  }
 ]
}